### ISSUE TITLE
SETUP - Create database

### ISSUE THREAD

**Issue by OnyJ** [OnyJ/MasterMonster_back#4]
## Why

On a besoin de créer la BDD pour pouvoir créer des collections a l'intérieur afin de stocker des données importantes au jeu

## How

- [ ] utilisation de MongoDB pour la base de données car adaptée au projet de jeux 
  ```
  npm install mongodb
  ```
  
- [ ] créer le fichier `./docker-compose.yml` : 
  ```
  version: '3.8'
  
  services:
    server:
      build: .
      ports:
        - "3000:3000"
      depends_on:
        - mongo
      environment:
        - DB_URI=mongodb://mongo:27017
      volumes:
        - .:/app
      restart: always
  
    mongo:
      image: mongo:6
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
  
  volumes:
    mongo-data:
  ```
  
- [ ] initialiser le `package.json` si ce n'est pas déjà fait
  ```
  npm init -y
  ```

- [ ] installer mongodb et ws
  ```
  npm install ws mongodb
  ```

- [ ] dockeriser : 
  - [ ] créer `.dockerignore` à la racine : 
  ```
  # contenu de dockerignore : 
  node_modules
  npm-debug.log
  ```
  - [ ] dockerfile
    ```js
    # Base image
    FROM node:20
    
    # Créer dossier app
    WORKDIR /app
    
    # Copier les fichiers
    COPY package*.json ./
    RUN npm install
    COPY . .
    
    # Lancer le serveur WebSocket
    CMD ["node", "server.js"]
    ```
  - [ ] Lancer le projet
    ```
    docker-compose up --build
    ```

## Must Have

(résultat attendu)

- [ ] on doit pouvoir créer des tables dans la BDD
- [ ] on doit pouvoir se connecter à la BDD via le jeu
- [ ] sécurité - on ne doit pas pouvoir se connecter à la BDD de l'extérieur
- [ ] sécurité - on ne doit pas pouvoir se connecter à la BDD avec un logiciel tiers

## Reading List

Fonctionnement de la base de données avec JSON et Websockets
```
Client <---> WebSocket (Node.js) <--- Objet JSON en RAM
                        |
               [Sauvegarde/Chargement]
                        |
             Base de données SQL/NoSQL
```
