### ISSUE TITLE
SETUP - CI/CD Back

### ISSUE THREAD

**Issue by OnyJ** [OnyJ/MasterMonster_back#5]
## Why
Il est important de livrer un code fiable et cela passe par des tests qui doivent s'exécuter lors d'un push sur la branche.
Si les tests passent alors la CI build le container Docker sinon elle ne build pas pour ne pas prendre inutilement des ressources.

## How
- Installation de Jest pour les tests
```
npm install --save-dev jest
```

- ajouter cette ligne dans package.json pour pouvoir lancer les tests
```json

  "scripts": {
    "test": "jest"
  }
```

- Créer le fichier .github/workflows/ci.yml
```
name: CI - Tests Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run tests
        run: npm test

      - name: ❌ Fail if no tests are found
        run: |
          TEST_COUNT=$(npx jest --listTests | wc -l)
          echo "🔍 Found $TEST_COUNT test file(s)"
          if [ "$TEST_COUNT" -eq 0 ]; then
            echo "❌ No tests found. Failing build."
            exit 1
          fi

```

## Must have
- [ ] Il doit y avoir des tests
- [ ] les tests doivent passer pour build le container
- [ ] Le projet doit build le container lorsque la CI est OK
- [ ] Le test ne doit pas build le container lorsque la CI fail
